In [1]:
import pickle
import json
import time, datetime
import numpy as np
import torch

def read_pickle(file):
    with open(file, 'rb') as f:
        ret = pickle.load(f)
    return ret

def read_json(file):
    with open(file, 'r') as f:
        ret = [json.loads(line) for line in f]
    return ret

def write_pickle(file, data):
    with open(file, 'wb') as fw:
        pickle.dump(data, fw)

In [2]:
filepath = '../yelp_dataset/filtered/'
jsonpath = '../yelp_dataset/json/'

In [5]:
reviews = read_pickle(filepath+'reviews.pickle')
# reviews = read_pickle(filepath+'reviews-small.pickle')
print(len(reviews))

742969


In [4]:
# users_comp = read_pickle(filepath+'users-complete.pickle')
users = read_pickle(filepath+'users-complete.pickle')
# users = read_pickle(filepath+'users-small.pickle')
print(len(users))

12642


In [3]:
# busi_comp = read_pickle(filepath+'businesses-complete.pickle')
businesses = read_pickle(filepath+'businesses-complete.pickle')
# businesses = read_pickle(filepath+'businesses-small.pickle')
print(len(businesses))

12852


In [6]:
print(type(reviews))
print(reviews[0].keys())
print(len(reviews))
print(type(users))
for u in users:
    print(u.keys())
    break
for b in businesses:
    print(b.keys())
    break

<class 'list'>
dict_keys(['user_id', 'date', 'useful', 'review_id', 'text', 'business_id', 'stars', 'funny', 'cool'])
742969
<class 'list'>
dict_keys(['compliment_hot', 'compliment_note', 'average_stars', 'review_count', 'elite', 'cool', 'friends', 'yelping_since', 'compliment_profile', 'name', 'compliment_more', 'compliment_plain', 'compliment_photos', 'user_id', 'funny', 'compliment_funny', 'compliment_list', 'compliment_cute', 'useful', 'compliment_writer', 'fans', 'compliment_cool'])
dict_keys(['name', 'latitude', 'is_open', 'categories', 'review_count', 'postal_code', 'address', 'longitude', 'state', 'attributes', 'city', 'hours', 'stars', 'business_id'])


# Compute id2ind and ind2id

In [10]:
uinds = [i for i in range(len(users))]
uid2ind = {user['user_id']:ind for user, ind in zip(users, uinds)}
ind2uid = {ind:user['user_id'] for user, ind in zip(users, uinds)}

In [11]:
b_inds = [i for i in range(len(businesses))]
bid2ind = {business['business_id']:ind for business, ind in zip(businesses, b_inds)}
ind2bid = {ind:business['business_id'] for business, ind in zip(businesses, b_inds)}

In [12]:
cities = set(busi['city'] for busi in businesses)
c_inds = [i for i in range(len(cities))]
ct_id2ind = {city:ind for city, ind in zip(cities, c_inds)}
ind2ct_id = {ind:city for city, ind in zip(cities, c_inds)}

In [13]:
print(len(cities))
print(ct_id2ind)

7
{'Summerlin': 0, 'Dallas': 1, 'Henderson': 5, 'North Las Vegas': 2, 'Spring Valley': 3, 'Las Vegas': 4, 'Boulder City': 6}


In [14]:
categories = set(category.strip() for busi in businesses for category in busi['categories'].split(','))
ca_inds = [i for i in range(len(categories))]
ca_id2ind = {category:ind for category, ind in zip(categories, ca_inds)}
ind2ca_id = {ind:category for category, ind in zip(categories, ca_inds)}

In [10]:
print(len(categories))
# print(ca_id2ind)

NameError: name 'categories' is not defined

# Split data and compute adj matrix

In [16]:
def dataset_split(reviews, userid_to_num, businessid_to_num, train_ratio, valid_ratio, test_ratio, n_neg_sample):
    selected_reviews = []
    
    for review in reviews:
        filtered_review = {}
        filtered_review['user_id'] = userid_to_num[review['user_id']]
        filtered_review['business_id'] = businessid_to_num[review['business_id']]
        filtered_review['rate'] = 1.0
        filtered_review['timestamp'] = time.mktime(datetime.datetime.strptime(review['date'], '%Y-%m-%d %H:%M:%S').timetuple())
        selected_reviews.append(filtered_review)
        
    selected_reviews_sorted = sorted(selected_reviews, key=lambda k: k['timestamp']) # use the earlier data to train and the later data to test
    n_reviews = len(selected_reviews_sorted)
    train_size = int(n_reviews*train_ratio)
    valid_size = int(n_reviews*valid_ratio)
    train_data = [selected_reviews_sorted[index] for index in range(train_size)]
    valid_data = [selected_reviews_sorted[index] for index in range(train_size, train_size+valid_size)]
    test_data = [selected_reviews_sorted[index] for index in range(train_size+valid_size, n_reviews)]
    
    selected_users = set()
    selected_businesses = set()
    for review in train_data:
        selected_users.add(review['user_id'])
        selected_businesses.add(review['business_id'])
        
    eval_datas = [valid_data, test_data]
#     selected_eval_datas = [[] for _ in range(len(eval_datas))]
    selected_eval_datas = [[], []]
    for eval_index in range(len(eval_datas)):
        eval_data = eval_datas[eval_index]
        for review in eval_data:
            if review['user_id'] in selected_users and review['business_id'] in selected_businesses:
                selected_eval_datas[eval_index].append(review)
    selected_valid_data, selected_test_data = selected_eval_datas
    
    data_list = [train_data, selected_valid_data, selected_test_data]
#     data_for_user_list = [{} for _ in range(len(data_list))]
    data_for_user_list = [{}, {}, {}]
    train_data_for_item = set()
    for index in range(len(data_list)):
        data = data_list[index]
        data_for_user = data_for_user_list[index]
        for review in data:
            user = review['user_id']
            item = review['business_id']
            if index == 0:
                train_data_for_item.add(item)
            if user not in data_for_user:
                data_for_user[user] = [item]
            else:
                data_for_user[user].append(item)
    train_data_for_user, valid_data_for_user, test_data_for_user = data_for_user_list # dictionary of user_id:[item_id]
    
    with_neg_list = [valid_data_for_user, test_data_for_user]
#     data_with_neg_list = [[] for _ in range(len(with_neg_list))]
    data_with_neg_list = [[], []]
    for index in range(len(with_neg_list)):
        current_data = with_neg_list[index]
        for user in current_data.keys():
            if user not in selected_users:
                continue
            user_eval = {} # a dict
            business_set = selected_businesses - set(train_data_for_user[user]) - set(current_data[user]) # items not existed in this user's records
            sample_businesses = np.random.choice(list(business_set), size=n_neg_sample, replace=False)    # sample is random.choice
            user_eval['user_id'] = user
            user_eval['pos_business_id'] = current_data[user]
            user_eval['neg_business_id'] = list(sample_businesses)
            data_with_neg_list[index].append(user_eval)
    valid_with_neg, test_with_neg = data_with_neg_list
    
    return train_data, selected_valid_data, selected_test_data, valid_with_neg, test_with_neg

In [11]:
# get adjs
def get_adj_matrix(uid2ind, bid2ind, city_id2ind, cat_id2ind, users, businesses, reviews):
    """
    metapaths: UB, UUB, UBUB, UBCaB, UBCiB
    """
    tot_users = len(uid2ind)  # tot for total
    tot_business = len(bid2ind)
    tot_city = len(city_id2ind)
    tot_category = len(cat_id2ind)
    print(tot_users, tot_business, tot_city, tot_category)
    #relation U-U
    adj_UU = np.zeros([tot_users, tot_users])
    adj_UB = np.zeros([tot_users, tot_business])
    adj_BCa = np.zeros([tot_business, tot_category])
    adj_BCi = np.zeros([tot_business, tot_city])
    adj_UCa = np.zeros([tot_users, tot_category])
    adj_UCi = np.zeros([tot_users, tot_city])
#     print(adj_BCi.shape)
    for user in users:
        if user['user_id'] not in uid2ind:
            continue
        user_id = uid2ind[user['user_id']]
        for friend in user['friends'].split(','):
            friend = friend.strip()
            if friend in uid2ind:
                friend_id = uid2ind[friend]
                adj_UU[user_id][friend_id] = 1
                adj_UU[friend_id][user_id] = 1
    for review in reviews:
#         user_id = uid2ind[review['user_id']]
#         business_id = bid2ind[review['business_id']]
        user_id = review['user_id']
        business_id = review['business_id']
        bid = ind2bid[business_id]
        for b in businesses:
            if b['business_id'] == bid:
                categories = b['categories'].split(',')
#                 print(categories)
                ci_id = city_id2ind[b['city']]
                adj_UCi[user_id][ci_id] = 1        # TODO: here matters. += 1 or =1
                for ca in categories:
#                     print(ca)
                    ca = ca.strip()
                    ca_id = cat_id2ind[ca]
                    adj_UCa[user_id][ca_id] = 1    # TODO: here matters, let all edge be 1 or be the number of edges
                break
        adj_UB[user_id][business_id] = 1
        
    #relation B_Ca B_Ci
    for business in businesses:
        if business['business_id'] not in bid2ind:
            continue
        business_id = bid2ind[business['business_id']]
        city_id = city_id2ind[business['city']]
        print("business_id: %d, city_id: %d" % (business_id, city_id))
        adj_BCi[business_id][city_id] = 1
        
        # more than one category for a business
        for category in business['categories'].split(','):
            category = category.strip()
            category_id = cat_id2ind[category]
            adj_BCa[business_id][category_id] = 1

    #metapath
    adj_UUB = adj_UU.dot(adj_UB)

    adj_UBU = adj_UB.dot(adj_UB.T)

    adj_UBUB = adj_UBU.dot(adj_UB)

    adj_UBCa = adj_UB.dot(adj_BCa)
    adj_UBCaB = adj_UBCa.dot(adj_BCa.T)

    adj_UBCi = adj_UB.dot(adj_BCi)
    adj_UBCiB = adj_UBCi.dot(adj_BCi.T)

    adj_UCaB = adj_UCa.dot(adj_BCa.T)
    adj_UCiB = adj_UCi.dot(adj_BCi.T)
    
    adj_UCaBCi = adj_UCaB.dot(adj_BCi)
    adj_UCiBCa = adj_UCiB.dot(adj_BCa)
    
    adj_UCaBCiB = adj_UCaBCi.dot(adj_BCi.T)
    adj_UCiBCaB = adj_UCiBCa.dot(adj_BCa.T)
    
    return adj_UB, adj_UUB, adj_UBUB, adj_UBCaB, adj_UBCiB, adj_UCaB, adj_UCiB, adj_UCaBCiB, adj_UCiBCaB


In [18]:
train_data, valid_data, test_data, valid_with_neg_sample, test_with_neg_sample \
    = dataset_split(reviews, uid2ind, bid2ind, 0.8, 0.1, 0.1, 50)

In [22]:
print(type(train_data))
print(train_data[0])
print(reviews[0])
print(len(train_data))

<class 'list'>
{'business_id': 181, 'rate': 1.0, 'user_id': 21, 'timestamp': 1116877827.0}
{'review_id': 'kbtscdyz6lvrtGjD1quQTg', 'cool': 0, 'user_id': 'FIk4lQQu1eTe2EpzQ4xhBA', 'stars': 4.0, 'date': '2011-11-30 02:11:15', 'business_id': '8mIrX_LrOnAqWsB5JrOojQ', 'funny': 0, 'useful': 0, 'text': 'Like walking back in time, every Saturday morning my sister and I was in a bowling league and after we were done, we\'d spend a few quarters playing the pin ball machines until our mother came to pick us up.\n\nMy sister was daring and play the machines hard, she was afraid of that "tilt" showing up and freezing the game.  I, on the other hand was a bit more gentler and wanted to make sure I got my quarter\'s worth.\n\nThis place has rows and rows of machines, some are really old and some are more of a mid 80\'s theme.  There is even a Ms pac man!  It was fun to spend an afternoon playing the machines and remembering all the fun of my early teen years.'}
36692


In [23]:
path = '../yelp_dataset/rates/'
filenames = ['train_data', 'valid_data', 'test_data', 'valid_with_neg_sample', 'test_with_neg_sample']
objs = [train_data, valid_data, test_data, valid_with_neg_sample, test_with_neg_sample]
for file, obj in zip(filenames, objs):
    write_pickle(path+file+'.pickle', obj)

In [12]:
# get adj matrices
adj_UB, adj_UUB, adj_UBUB, adj_UBCaB, adj_UBCiB, adj_UCaB, adj_UCiB, adj_UCaBCiB, adj_UCiBCaB \
    = get_adj_matrix(uid2ind, bid2ind, ct_id2ind, ca_id2ind, users, businesses, train_data)

12642 12852 160 659
business_id: 0, city_id: 11
business_id: 1, city_id: 143
business_id: 2, city_id: 158
business_id: 3, city_id: 120
business_id: 4, city_id: 158
business_id: 5, city_id: 0
business_id: 6, city_id: 11
business_id: 7, city_id: 22
business_id: 8, city_id: 37
business_id: 9, city_id: 37
business_id: 10, city_id: 135
business_id: 11, city_id: 143
business_id: 12, city_id: 120
business_id: 13, city_id: 0
business_id: 14, city_id: 158
business_id: 15, city_id: 158
business_id: 16, city_id: 0
business_id: 17, city_id: 120
business_id: 18, city_id: 37
business_id: 19, city_id: 93
business_id: 20, city_id: 22
business_id: 21, city_id: 158
business_id: 22, city_id: 103
business_id: 23, city_id: 69
business_id: 24, city_id: 135
business_id: 25, city_id: 37
business_id: 26, city_id: 0
business_id: 27, city_id: 96
business_id: 28, city_id: 42
business_id: 29, city_id: 37
business_id: 30, city_id: 93
business_id: 31, city_id: 0
business_id: 32, city_id: 158
business_id: 33, city_id

business_id: 1955, city_id: 78
business_id: 1956, city_id: 103
business_id: 1957, city_id: 159
business_id: 1958, city_id: 4
business_id: 1959, city_id: 158
business_id: 1960, city_id: 135
business_id: 1961, city_id: 120
business_id: 1962, city_id: 158
business_id: 1963, city_id: 0
business_id: 1964, city_id: 158
business_id: 1965, city_id: 158
business_id: 1966, city_id: 120
business_id: 1967, city_id: 22
business_id: 1968, city_id: 120
business_id: 1969, city_id: 158
business_id: 1970, city_id: 158
business_id: 1971, city_id: 19
business_id: 1972, city_id: 4
business_id: 1973, city_id: 120
business_id: 1974, city_id: 158
business_id: 1975, city_id: 158
business_id: 1976, city_id: 143
business_id: 1977, city_id: 0
business_id: 1978, city_id: 103
business_id: 1979, city_id: 37
business_id: 1980, city_id: 69
business_id: 1981, city_id: 22
business_id: 1982, city_id: 0
business_id: 1983, city_id: 22
business_id: 1984, city_id: 120
business_id: 1985, city_id: 158
business_id: 1986, city_i

business_id: 3884, city_id: 158
business_id: 3885, city_id: 158
business_id: 3886, city_id: 120
business_id: 3887, city_id: 96
business_id: 3888, city_id: 135
business_id: 3889, city_id: 120
business_id: 3890, city_id: 120
business_id: 3891, city_id: 159
business_id: 3892, city_id: 22
business_id: 3893, city_id: 103
business_id: 3894, city_id: 120
business_id: 3895, city_id: 143
business_id: 3896, city_id: 143
business_id: 3897, city_id: 120
business_id: 3898, city_id: 22
business_id: 3899, city_id: 22
business_id: 3900, city_id: 0
business_id: 3901, city_id: 158
business_id: 3902, city_id: 64
business_id: 3903, city_id: 0
business_id: 3904, city_id: 19
business_id: 3905, city_id: 150
business_id: 3906, city_id: 158
business_id: 3907, city_id: 120
business_id: 3908, city_id: 69
business_id: 3909, city_id: 143
business_id: 3910, city_id: 22
business_id: 3911, city_id: 158
business_id: 3912, city_id: 78
business_id: 3913, city_id: 88
business_id: 3914, city_id: 158
business_id: 3915, cit

business_id: 5884, city_id: 37
business_id: 5885, city_id: 120
business_id: 5886, city_id: 143
business_id: 5887, city_id: 120
business_id: 5888, city_id: 0
business_id: 5889, city_id: 135
business_id: 5890, city_id: 22
business_id: 5891, city_id: 103
business_id: 5892, city_id: 22
business_id: 5893, city_id: 130
business_id: 5894, city_id: 22
business_id: 5895, city_id: 122
business_id: 5896, city_id: 78
business_id: 5897, city_id: 11
business_id: 5898, city_id: 135
business_id: 5899, city_id: 120
business_id: 5900, city_id: 158
business_id: 5901, city_id: 143
business_id: 5902, city_id: 158
business_id: 5903, city_id: 120
business_id: 5904, city_id: 103
business_id: 5905, city_id: 22
business_id: 5906, city_id: 93
business_id: 5907, city_id: 158
business_id: 5908, city_id: 12
business_id: 5909, city_id: 158
business_id: 5910, city_id: 158
business_id: 5911, city_id: 103
business_id: 5912, city_id: 135
business_id: 5913, city_id: 44
business_id: 5914, city_id: 158
business_id: 5915, c

business_id: 7878, city_id: 53
business_id: 7879, city_id: 135
business_id: 7880, city_id: 143
business_id: 7881, city_id: 96
business_id: 7882, city_id: 158
business_id: 7883, city_id: 103
business_id: 7884, city_id: 99
business_id: 7885, city_id: 158
business_id: 7886, city_id: 69
business_id: 7887, city_id: 22
business_id: 7888, city_id: 143
business_id: 7889, city_id: 158
business_id: 7890, city_id: 135
business_id: 7891, city_id: 69
business_id: 7892, city_id: 22
business_id: 7893, city_id: 120
business_id: 7894, city_id: 158
business_id: 7895, city_id: 11
business_id: 7896, city_id: 120
business_id: 7897, city_id: 120
business_id: 7898, city_id: 69
business_id: 7899, city_id: 22
business_id: 7900, city_id: 22
business_id: 7901, city_id: 0
business_id: 7902, city_id: 158
business_id: 7903, city_id: 37
business_id: 7904, city_id: 46
business_id: 7905, city_id: 22
business_id: 7906, city_id: 43
business_id: 7907, city_id: 158
business_id: 7908, city_id: 102
business_id: 7909, city_i

business_id: 9888, city_id: 103
business_id: 9889, city_id: 143
business_id: 9890, city_id: 158
business_id: 9891, city_id: 158
business_id: 9892, city_id: 37
business_id: 9893, city_id: 158
business_id: 9894, city_id: 158
business_id: 9895, city_id: 158
business_id: 9896, city_id: 143
business_id: 9897, city_id: 120
business_id: 9898, city_id: 135
business_id: 9899, city_id: 64
business_id: 9900, city_id: 103
business_id: 9901, city_id: 11
business_id: 9902, city_id: 19
business_id: 9903, city_id: 158
business_id: 9904, city_id: 69
business_id: 9905, city_id: 135
business_id: 9906, city_id: 158
business_id: 9907, city_id: 120
business_id: 9908, city_id: 37
business_id: 9909, city_id: 158
business_id: 9910, city_id: 143
business_id: 9911, city_id: 158
business_id: 9912, city_id: 0
business_id: 9913, city_id: 103
business_id: 9914, city_id: 120
business_id: 9915, city_id: 158
business_id: 9916, city_id: 158
business_id: 9917, city_id: 158
business_id: 9918, city_id: 120
business_id: 991

business_id: 11908, city_id: 158
business_id: 11909, city_id: 14
business_id: 11910, city_id: 0
business_id: 11911, city_id: 120
business_id: 11912, city_id: 120
business_id: 11913, city_id: 22
business_id: 11914, city_id: 158
business_id: 11915, city_id: 69
business_id: 11916, city_id: 120
business_id: 11917, city_id: 22
business_id: 11918, city_id: 0
business_id: 11919, city_id: 158
business_id: 11920, city_id: 22
business_id: 11921, city_id: 158
business_id: 11922, city_id: 22
business_id: 11923, city_id: 0
business_id: 11924, city_id: 120
business_id: 11925, city_id: 120
business_id: 11926, city_id: 16
business_id: 11927, city_id: 158
business_id: 11928, city_id: 42
business_id: 11929, city_id: 42
business_id: 11930, city_id: 96
business_id: 11931, city_id: 158
business_id: 11932, city_id: 120
business_id: 11933, city_id: 32
business_id: 11934, city_id: 158
business_id: 11935, city_id: 120
business_id: 11936, city_id: 78
business_id: 11937, city_id: 158
business_id: 11938, city_id:

In [37]:
print(adj_UB.shape)
print(adj_UBCaB[0:100][0:100])
print(adj_UCiBCaB[0:100][0:100])
print(adj_UCaB[0:100][0:100])
print(adj_UB.shape, adj_UCiBCaB.shape)

(648, 637)
[[395.  92. 110. ... 361. 216. 454.]
 [100.  14.  21. ...  92.  58. 107.]
 [182.  46.  54. ... 195. 102. 214.]
 ...
 [ 91.  26.  22. ...  79.  47.  95.]
 [387.  86. 109. ... 353. 224. 415.]
 [114.  70.  19. ... 170.  65. 116.]]
[[1140.  271.  318. ... 1072.  644. 1227.]
 [1138.  270.  318. ... 1069.  640. 1223.]
 [1138.  270.  318. ... 1069.  640. 1223.]
 ...
 [1138.  270.  318. ... 1069.  640. 1223.]
 [1138.  270.  318. ... 1069.  640. 1223.]
 [1025.  259.  282. ...  995.  582. 1104.]]
[[11.  4.  5. ...  9.  5. 13.]
 [10.  1.  4. ...  5.  4. 13.]
 [ 9.  3.  7. ...  9.  4. 13.]
 ...
 [10.  4.  4. ...  5.  4. 10.]
 [11.  4.  7. ...  8.  5. 13.]
 [ 9.  4.  2. ...  9.  4. 10.]]
(648, 637) (648, 637)


In [13]:
adjs = [adj_UB, adj_UUB, adj_UBUB, adj_UBCaB, adj_UBCiB, adj_UCaB, adj_UCiB, adj_UCaBCiB, adj_UCiBCaB]
filenames = ['adj_UB', 'adj_UUB', 'adj_UBUB', 'adj_UBCaB', 'adj_UBCiB', 'adj_UCaB', 'adj_UCiB', 'adj_UCaBCiB', 'adj_UCiBCaB']
path = '../yelp_dataset/adjs/'
for adj, file in zip(adjs, filenames):
    write_pickle(path+file+'.pickle', adj)

In [27]:
filenames = ['uid2ind', 'bid2ind', 'ct_id2ind', 'ca_id2ind', 'ind2uid', 'ind2bid', 'ind2ct_id', 'ind2ca_id']
maps = [uid2ind, bid2ind, ct_id2ind, ca_id2ind, ind2uid, ind2bid, ind2ct_id, ind2ca_id]
path = '../yelp_dataset/adjs/'
for mapping, file in zip(maps, filenames):
    write_pickle(path+file+'.pickle', mapping)

# Experiments

In [10]:
# load dictionaries
path = '../yelp_dataset/adjs/'
uid2ind = read_pickle(path+'uid2ind.pickle')
bid2ind = read_pickle(path+'bid2ind.pickle')
ct_id2ind = read_pickle(path+'ct_id2ind.pickle')
ca_id2ind = read_pickle(path+'ca_id2ind.pickle')
ind2uid = read_pickle(path+'ind2uid.pickle')
ind2bid = read_pickle(path+'ind2bid.pickle')
ind2ct_id = read_pickle(path+'ind2ct_id.pickle')
ind2ca_id = read_pickle(path+'ind2ca_id.pickle')

In [30]:
del reviews

NameError: name 'reviews' is not defined

In [112]:
train_data = read_pickle('../yelp_dataset/rates/train_data.pickle')
print(type(train_data))

<class 'list'>


In [113]:
print(train_data[0])

{'business_id': 181, 'rate': 1.0, 'user_id': 21, 'timestamp': 1116877827.0}


In [99]:
def make_embedding(user_features, item_features):
    user_concat = torch.cat(user_features, 1)
    item_concat = torch.cat(item_features, 1)
    X = []
    for user in user_concat:
        tmp = [torch.cat([user,item], 0).unsqueeze(0) for item in item_concat]
        print("tmp[0].shape", tmp[0].shape)
        tmp = torch.cat(tmp, 0)
        X.append(tmp)
    X = torch.cat(X, 0)
    return X

In [3]:
def load_feature(feature_path, metapaths):
    user_features = [read_pickle(feature_path+metapath+'_user.pickle') for metapath in metapaths]
    item_features = [read_pickle(feature_path+metapath+'_item.pickle') for metapath in metapaths]
        
    return user_features, item_features


In [106]:
def make_labels(Y, n_user, n_item):
    r"""
    Parameter
    ---------
    Y: list of dict
        saves the interaction information in COO form
    
    Return
    ------
    ret: torch.tensor
        still in COO form
    """
    indices = np.array(([y['user_id'] for y in Y], [y['business_id'] for y in Y]))
    values = np.array([1. for y in Y])
    device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
    ret = torch.sparse_coo_tensor(indices, values, size=(n_user,n_item),
                                  dtype=torch.float32, device=device, requires_grad=False)
    return ret

In [115]:
Y = make_labels(train_data, 648, 637)
print(Y.shape)
print(Y)
print(type(Y))
dense = Y.to_dense()
x = [0, 1, 2, 3]
y = [0, 1, 2, 3]
print(dense)
dense[x, y]
# print(dense[99])

torch.Size([648, 637])
tensor(indices=tensor([[ 21,  99,  99,  ..., 530, 568, 118],
                       [181, 569, 290,  ...,  34,   9, 201]]),
       values=tensor([1., 1., 1.,  ..., 1., 1., 1.]),
       device='cuda:0', size=(648, 637), nnz=36692, layout=torch.sparse_coo)
<class 'torch.Tensor'>
tensor([[0., 0., 0.,  ..., 1., 1., 0.],
        [0., 0., 0.,  ..., 0., 0., 1.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]], device='cuda:0')


tensor([0., 0., 0., 0.], device='cuda:0')

In [4]:
featurepath = '../yelp_dataset/mf_features/'
metapaths = ['UB', 'UUB', 'UBUB', 'UBCaB', 'UBCiB']

In [8]:
user_features, item_features = load_feature(featurepath, metapaths)

In [104]:
# this is for test
user_features = tuple(torch.Tensor(np.zeros((3, 3))) for i in range(2)) # two 3*3 matrices
item_features = tuple(torch.Tensor(np.ones((5, 3))) for i in range(2))  # two 5*3 matrices

print("user_features:", user_features)

user_concat = torch.cat(user_features, 1)
print(user_concat[:, 0:2])
print("user_concat:", user_concat)
item_concat = torch.cat(item_features, 1)
print("item_concat:", item_concat)
user = user_concat[0]
item = item_concat[0]
print(user, item)
user = user_concat[0].view(1, 2, 3)
item = item_concat[0].view(1, 2, 3)
print(user, item)
ui_concat = torch.cat([user, item], 1)
print("ui_concat:", ui_concat)

user_features: (tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]), tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]))
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
user_concat: tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])
item_concat: tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])
tensor([0., 0., 0., 0., 0., 0.]) tensor([1., 1., 1., 1., 1., 1.])
tensor([[[0., 0., 0.],
         [0., 0., 0.]]]) tensor([[[1., 1., 1.],
         [1., 1., 1.]]])
ui_concat: tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [1., 1., 1.],
         [1., 1., 1.]]])


In [100]:
X = make_embedding(user_features, item_features)
print(X)

tmp[0].shape torch.Size([1, 12])
tmp[0].shape torch.Size([1, 12])
tmp[0].shape torch.Size([1, 12])
tensor([[0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.]])


In [61]:
print(X.shape)

torch.Size([648, 637, 100])


In [6]:
def filter_rare_node(users, businesses, reviews, user_threshold, business_threshold, friend_threshold):
    continue_filter = True
    filtered_users = set()
    filtered_businesses = set()
    while(continue_filter):
        continue_filter = False
        user_interact_num = {}
        business_interact_num = {}
        user_business_interact = set()
        for review in reviews:
            if not review['date']:
                continue
            user_id = review['user_id']
            business_id = review['business_id']
            user_business = str(user_id)+str(business_id)
            if user_business not in user_business_interact:
                user_interact_num[user_id] = user_interact_num.get(user_id, 0) + 1
                business_interact_num[business_id] = business_interact_num.get(business_id, 0) + 1
                user_business_interact.add(user_business)
        filtered_review_users = set(u for u in user_interact_num.keys() if user_interact_num[u]>=user_threshold)
        filtered_review_businesses = set(b for b in business_interact_num.keys() if business_interact_num[b]>=business_threshold)
        if (filtered_users != filtered_review_users) or (filtered_businesses != filtered_review_businesses):
            continue_filter = True
        # filter step 2
        #filter user and business
        user_friends_dict = {}
        for user in users:
            user_id = user['user_id']
            if user_id not in filtered_review_users:
                continue
            if not user['friends']:
                continue
            filtered_friends = [friend.strip() for friend in user['friends'].split(',') if friend.strip() in filtered_review_users]
            if len(filtered_friends) >= friend_threshold:
                user_friends_dict[user_id] = filtered_friends
        continue_inside = True
        while (continue_inside):
            friends = {}
            continue_inside = False
            for user, user_friends in user_friends_dict.items():
                filtered_friends = [friend for friend in user_friends if friend in user_friends_dict]
                if len(filtered_friends) >= friend_threshold:
                    friends[user] = filtered_friends
                else:
                    continue_inside = True
            user_friends_dict = deepcopy(friends)
        filtered_users = set(user_friends_dict.keys())
        filtered_businesses_list = []
        for business in businesses:
            business_id = business['business_id']
            if business_id not in filtered_review_businesses:
                continue
            if not business['categories']:
                continue
            if not business['city']:
                continue
            filtered_businesses_list.append(business_id)
        filtered_businesses = set(filtered_businesses_list)
        filtered_review = []
        user_business_interact = set()
        for review in reviews:
            if not review['date']:
                continue
            if (review['user_id'] in filtered_users) and (review['business_id'] in filtered_businesses):
                user_id = review['user_id']
                business_id = review['business_id']
                user_business = str(user_id) + str(business_id)
                if user_business not in user_business_interact:
                    filtered_review.append(review)
                    user_business_interact.add(user_business)
        reviews = deepcopy(filtered_review)
        print(len(list(filtered_users)))
        print(len(list(filtered_businesses)))
        print(len(reviews))
        print('filter loop')
    print('filter complete')
    return filtered_users, filtered_businesses, filtered_review


In [24]:
from copy import deepcopy
users_small, busi_small, reviews_small = filter_rare_node(users, businesses, reviews, 40, 44, 4)
print(len(users_small))
print(len(busi_small))
print(len(reviews_small))

5647
5153
349913
filter loop
3613
3426
236230
filter loop
2707
2445
174828
filter loop
2095
1953
139223
filter loop
1727
1574
115435
filter loop
1451
1350
100099
filter loop
1277
1222
89362
filter loop
1171
1082
80145
filter loop
1032
986
71864
filter loop
946
881
65722
filter loop
864
816
61480
filter loop
818
784
58698
filter loop
796
764
57019
filter loop
770
743
55129
filter loop
751
725
53627
filter loop
735
709
52327
filter loop
713
703
51216
filter loop
711
690
50583
filter loop
691
689
49752
filter loop
691
672
49025
filter loop
679
672
48564
filter loop
679
659
48005
filter loop
662
659
47346
filter loop
662
644
46705
filter loop
652
644
46319
filter loop
652
638
46064
filter loop
649
638
45947
filter loop
649
637
45904
filter loop
648
637
45865
filter loop
648
637
45865
filter loop
filter complete
648
637
45865


In [20]:
users_small = []
for user in users_comp:
    for u in users:
        if user['user_id'] == u:
            users_small.append(user)
print(len(users_small))
print(users_small[0].keys())

648
dict_keys(['elite', 'yelping_since', 'friends', 'average_stars', 'review_count', 'compliment_cute', 'compliment_note', 'user_id', 'compliment_hot', 'compliment_more', 'compliment_cool', 'cool', 'compliment_plain', 'compliment_funny', 'compliment_writer', 'fans', 'compliment_photos', 'compliment_list', 'name', 'compliment_profile', 'useful', 'funny'])


In [21]:
busi_small = []
for busi in busi_comp:
    for b in businesses:
        if busi['business_id'] == b:
            busi_small.append(busi)
print(len(busi_small))
print(busi_small[0].keys())

637
dict_keys(['categories', 'is_open', 'hours', 'attributes', 'address', 'longitude', 'name', 'state', 'postal_code', 'latitude', 'business_id', 'review_count', 'stars', 'city'])


In [22]:
write_pickle('../yelp_dataset/filtered/users-small.pickle', users_small)

In [23]:
write_pickle('../yelp_dataset/filtered/businesses-small.pickle', busi_small)

In [27]:
write_pickle('../yelp_dataset/filtered/reviews-small.pickle', reviews_small)

In [26]:
# test sparsity
adj = read_pickle('../yelp_dataset/adjs/adj_UBCiB.pickle')
print(type(adj))
# for i in adj_UB

<class 'numpy.ndarray'>


In [27]:
import scipy.sparse as sp
sparse = sp.csr_matrix(adj)

In [28]:
nnz = sparse.nnz
size = adj.shape[0] * adj.shape[1]
print(nnz / size)

0.9474751439037153


注意到除了UB的稠密度只有0.08，其余的都有至少0.85以上，说明metapath的邻接矩阵实际上很稠密

In [62]:
x = torch.ones(10)*10
x[3] = 7
x = x.unsqueeze(1)
print(x)
V = torch.ones(10, 5)
V[:, 3] *= 3
print(V)
# print(torch.matmul(x, V))
out = torch.mul(x, V).sum(1, keepdim=True)
print(out)
out_t = out.sum(0).squeeze()
print(out_t.size())
print(out_t)

tensor([[10.],
        [10.],
        [10.],
        [ 7.],
        [10.],
        [10.],
        [10.],
        [10.],
        [10.],
        [10.]])
tensor([[1., 1., 1., 3., 1.],
        [1., 1., 1., 3., 1.],
        [1., 1., 1., 3., 1.],
        [1., 1., 1., 3., 1.],
        [1., 1., 1., 3., 1.],
        [1., 1., 1., 3., 1.],
        [1., 1., 1., 3., 1.],
        [1., 1., 1., 3., 1.],
        [1., 1., 1., 3., 1.],
        [1., 1., 1., 3., 1.]])
tensor([[70.],
        [70.],
        [70.],
        [49.],
        [70.],
        [70.],
        [70.],
        [70.],
        [70.],
        [70.]])
torch.Size([])
tensor(679.)


In [64]:
out_t = out_t.repeat(1, 2)
print(out_t)
out_t[0][1] = -out_t[0][0]
print(out_t[0][1])
print(out_t)

tensor([[ 679., -679.,  679., -679.]])
tensor(-679.)


AttributeError: 'Tensor' object has no attribute 'astype'

# Process valid dataset

In [7]:
valid_data = read_pickle('../yelp_dataset/rates/valid_with_neg_sample.pickle')
train_data = read_pickle('../yelp_dataset/rates/train_data.pickle')

In [9]:
len(train_data)

594375

In [49]:
pos = [[y['user_id'], pos_id, 1] for y in valid_data for pos_id in y['pos_business_id']]
neg = [[y['user_id'], neg_id, 0] for y in valid_data for neg_id in y['neg_business_id']]
ret = pos + neg
ret[0:100]
ret_array = np.array(ret, dtype=np.int64)
ret_array.dtype

dtype('int64')

In [39]:
print(len(valid_data[1]['neg_business_id']))

50


In [33]:
t_set = set(i for i in range(10))
# t_set = [i for i in range(10)]
t_array = np.asarray(list(t_set))
t_tensor = torch.as_tensor(t_array).repeat(2, 1)
print(t_tensor)
print(torch.topk(t_tensor, 2, dim=0))

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
torch.return_types.topk(
values=tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]),
indices=tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]))


In [173]:
class FMG_YelpDataset(Dataset):
    def __init__(self, interaction_data, n_user, n_item, neg_sample_n, mode, cuda=False):
        r"""
        Parameters
        ----------
        data: list of dict
        
        neg_sample_n: int,
            number of negative samples to be sampled
            
        mode: 'train', 'valid' or 'test',
            among which 'valid' and 'test' have the same functions
            
        Returns
        -------
        If mode == 'train':
        users: list of user ids
        
        items: list of business ids
        
        labels: corresponding labels
        
        If mode == 'valid' or 'test':
        user: list, 
            only one user id, but list size is len(items)
        
        items: list,
            positive samples and negative samples
            
        labels: corresponding labels
        """
        super().__init__()
        self.neg_sample_n = neg_sample_n
        self.mode = mode
        self.n_user = n_user
        self.n_item = n_item
        self.item_ids = set(i for i in range(self.n_item))
        self.device = torch.device('cuda:0' if cuda else 'cpu')

        if self.mode == 'train':
            pos_sampleset_list = [set() for i in range(self.n_user)]
            for y in interaction_data:
                pos_sampleset_list[y['user_id']].add(y['business_id'])            
            self.pos_sampleset_list = pos_sampleset_list    # used for train set
            self.data = torch.tensor(np.asarray([[y['user_id'], y['business_id'], 1] for y in interaction_data]), 
                                     device=self.device)

        elif self.mode == 'valid' or self.mode == 'test':
            self.data = []
            for input in interaction_data:
                pos = [i for i in input['pos_business_id']]
                neg = [i for i in input['neg_business_id']]
                items = pos + neg[0:self.neg_sample_n]
                user = [input['user_id']] * len(items)
                labels = [1] * len(pos) + [0] * self.neg_sample_n
                self.data.append([torch.tensor(np.asarray(user), device=self.device), 
                                  torch.tensor(np.asarray(items),device=self.device), 
                                  torch.tensor(np.asarray(labels), device=self.device)])
        
    def __getitem__(self, index):
        r"""
        ps: index is a number.
        
        return the uid and all pos bids and neg bids, along with labels.
        
        all in python list
        """
        if self.mode == 'train':
            pos_ind = self.data[index][0:2]
            user = pos_ind[0].item()    # user id
            pos_ind = pos_ind.unsqueeze(0)
            neg_sample_array = np.asarray(list(self.item_ids - self.pos_sampleset_list[user]))
            neg_samples = np.random.choice(neg_sample_array, self.neg_sample_n, replace=False)
            print("test: ", [user, neg_samples[0]])
            neg_inds = torch.tensor(np.asarray([[user, neg_sample] for neg_sample in neg_samples]), device=self.device)

            indices = torch.cat((pos_ind, neg_inds), 0)
            labels = torch.tensor(np.asarray([1] + [0]*self.neg_sample_n), device=self.device)
            return indices, labels

        elif self.mode == 'valid' or self.mode == 'test':
            r"""
            here the data contains 'pos_business_id' and 'neg_business_id' keys.
            """
            return self.data[index]
        
    def __len__(self):
        return len(self.data)    # available for both list and np.ndarray

In [174]:
dataset = FMG_YelpDataset(valid_data, len(users), len(businesses), neg_sample_n=3, mode='valid')
uid, bids, labels = dataset.__getitem__(2)
print(uid, bids, labels)
train_set = FMG_YelpDataset(train_data, len(users), len(businesses), neg_sample_n=4, mode='train')
print(train_set.__getitem__(2))

tensor([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]) tensor([ 10, 615,  73, 497, 540,  37, 398, 356, 255, 513, 251, 233,  12, 325,
        625, 484, 520, 353,  28, 137, 614]) tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0])
test:  [99, 617]
(tensor([[ 99, 290],
        [ 99, 617],
        [ 99, 278],
        [ 99, 180],
        [ 99, 235]]), tensor([1, 0, 0, 0, 0]))


In [147]:
valid = np.array(valid_data)
# valid = [1, 2, 3, 4, 5, 6]
# index = [2, 3, 4]
# input = valid[index]
# input['neg_business_id']

In [180]:
a = torch.randn(3, 4, 2)
print(a.shape)
print(a.squeeze(2).shape)
print(a.reshape(-1).shape)

torch.Size([3, 4, 2])
torch.Size([3, 4, 2])
torch.Size([24])
